// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAuFlMYdw5bd7ysuUJJOWXSNMtb_aZRYI',
    appId: '1:685241362577:web:1c1971e7acabaef3cbf730',
    messagingSenderId: '685241362577',
    projectId: 'listly-flutter',
    authDomain: 'listly-flutter.firebaseapp.com',
    storageBucket: 'listly-flutter.firebasestorage.app',
    measurementId: 'G-JRPFQQ3KM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOvXGXJ1G-mjCPwVOY9a8E1aYaCNUKA8',
    appId: '1:685241362577:android:a01f9a8a9f31f784cbf730',
    messagingSenderId: '685241362577',
    projectId: 'listly-flutter',
    storageBucket: 'listly-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-tgN5QGmK1tp5MSDeefzDxR4e5YuySmo',
    appId: '1:685241362577:ios:b49178dabf642bf9cbf730',
    messagingSenderId: '685241362577',
    projectId: 'listly-flutter',
    storageBucket: 'listly-flutter.firebasestorage.app',
    iosBundleId: 'com.example.listly',
  );

}